AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15

Style/CaseEquality:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 80
